##################################################################################################
# Mysql db out of cluster
# Setup external db using credentials: root/Welcome#1
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysqldb
subsets:
  - addresses:
    # FIXME: use the right IP
    - ip: 129.213.135.242
    ports:
      - protocol: TCP
        port: 3306