##################################################################################################
# Mysql db out of cluster
# Setup external db using credentials: root/Welcome#1
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ExternalName
  # FIXME: use the right IP
  externalName: 129.213.91.210
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-init
data:
  mysqlcs-init.sql: |
    DROP DATABASE IF EXISTS ratings;
    CREATE DATABASE ratings;
    USE ratings;

    CREATE TABLE `ratings` (
      `ReviewID` INT NOT NULL,
      `Rating` INT,
      PRIMARY KEY (`ReviewID`)
    );
    INSERT INTO ratings (ReviewID, Rating) VALUES (1, 5);
    INSERT INTO ratings (ReviewID, Rating) VALUES (2, 4);
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysqldb-init
spec:
  template:
    spec:
      initContainers:
       - name: init-mydb
         image: busybox
         command: ['/bin/sh', '-c']
         args: ['until nslookup mysqldb; do echo waiting for mysqldb; sleep 2; done;']
      containers:
      - name: mysqldb-init
        image: mysql:8.0.3
        command: ["/bin/sh", "-c"]
        args:
        - mysql -hmysqldb -uroot -p$MYSQL_ROOT_PASSWORD < /tmp/mysqlcs-init.sql;
        volumeMounts:
        - name: mysqldb-init-sql
          mountPath: /tmp
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootpasswd
      volumes:
      - name: mysqldb-init-sql
        configMap:
          name: mysqldb-init
      restartPolicy: Never
  backoffLimit: 4